# Generated by Django 4.2.4 on 2023-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_webseries_platform_webseries_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webseries',
            name='platform',
            field=models.ManyToManyField(blank=True, related_name='wbseries', to='api.streamplatform'),
        ),
    ]
